version: '3.8'

services:
  magiclists:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Navidrome Configuration
      - NAVIDROME_URL=${NAVIDROME_URL:-https://music.itsricky.com}
      - NAVIDROME_USERNAME=${NAVIDROME_USERNAME}
      - NAVIDROME_PASSWORD=${NAVIDROME_PASSWORD}
      - NAVIDROME_API_KEY=${NAVIDROME_API_KEY}
      
      # AI Configuration (OpenRouter)
      - AI_API_KEY=${AI_API_KEY}
      - AI_MODEL=${AI_MODEL:-openai/gpt-3.5-turbo}
      
      # Database Configuration
      - DATABASE_PATH=/app/data/magiclists.db
    volumes:
      - magiclists_data:/app/data
      - type: bind
        source: .env
        target: /app/.env
        read_only: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/artists"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  magiclists_data:
    driver: local